"""
Analytics & Statistics PDF Report Generator
CyberTrace - Zambia Police Service

Generate professional court-ready analytics and statistics reports
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime
import os


class AnalyticsPDFReport:
    """Generate PDF reports for analytics and statistics"""

    def __init__(self, data, case, investigator, logo_path=None):
        """
        Initialize PDF report generator

        Args:
            data: Dictionary containing analytics and statistics results
            case: Case model instance
            investigator: User model instance (investigator)
            logo_path: Path to police logo image
        """
        self.data = data
        self.case = case
        self.investigator = investigator
        self.logo_path = logo_path or 'app/static/img/zp_logo.jpg'
        self.styles = getSampleStyleSheet()
        self.zps_blue = colors.HexColor('#000663')
        self.zps_green = colors.HexColor('#008000')
        self._create_custom_styles()

    def _create_custom_styles(self):
        """Create custom paragraph styles for the report"""
        self.styles.add(ParagraphStyle(
            name='ReportTitle',
            parent=self.styles['Heading1'],
            fontSize=18,
            textColor=self.zps_blue,
            spaceAfter=12,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=self.zps_blue,
            spaceBefore=12,
            spaceAfter=6,
            fontName='Helvetica-Bold'
        ))
        self.styles.add(ParagraphStyle(
            name='BodyText',
            parent=self.styles['Normal'],
            fontSize=10,
            spaceAfter=6
        ))

    def generate(self, pdf_path):
        """Generate the PDF report at the specified path"""
        doc = SimpleDocTemplate(
            pdf_path,
            pagesize=A4,
            rightMargin=50,
            leftMargin=50,
            topMargin=50,
            bottomMargin=50
        )
        elements = []

        # Header
        elements.append(Paragraph('ZAMBIA POLICE SERVICE', self.styles['ReportTitle']))
        elements.append(Paragraph(
            'CONFIDENTIAL - AUTHORIZED USE ONLY',
            ParagraphStyle(
                name='Watermark',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.red,
                alignment=TA_CENTER
            )
        ))
        elements.append(Spacer(1, 12))

        # Case info table
        case_data = [
            ['Case Number:', self.case.case_number if hasattr(self.case, 'case_number') else str(self.case)],
            ['Investigator:', self.investigator.full_name if hasattr(self.investigator, 'full_name') else str(self.investigator)],
            ['Date:', datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')],
        ]
        t = Table(case_data, colWidths=[120, 350])
        t.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 20))

        # Report-specific content
        self._add_content(elements)

        # Footer
        elements.append(Spacer(1, 30))
        elements.append(Paragraph(
            'This report is generated by CyberTrace OSINT Platform for the Zambia Police Service.',
            ParagraphStyle(
                name='Footer',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.grey
            )
        ))

        doc.build(elements)

    def _add_content(self, elements):
        """Add analytics and statistics content to the report"""

        # Report title
        elements.append(Paragraph(
            '<b>Analytics &amp; Statistics Report</b>',
            self.styles['ReportTitle']
        ))
        elements.append(Spacer(1, 12))

        # --- Case Statistics ---
        elements.append(Paragraph('<b>CASE STATISTICS</b>', self.styles['SectionHeader']))

        case_stats = self.data.get('case_statistics', {})
        if case_stats:
            stats_rows = [
                ['Total Cases:', str(case_stats.get('total_cases', 'N/A'))],
                ['Open Cases:', str(case_stats.get('open_cases', 'N/A'))],
                ['Closed Cases:', str(case_stats.get('closed_cases', 'N/A'))],
                ['Pending Cases:', str(case_stats.get('pending_cases', 'N/A'))],
                ['Cases This Month:', str(case_stats.get('cases_this_month', 'N/A'))],
                ['Cases This Year:', str(case_stats.get('cases_this_year', 'N/A'))],
                ['Average Resolution Time:', str(case_stats.get('avg_resolution_time', 'N/A'))],
                ['Conviction Rate:', str(case_stats.get('conviction_rate', 'N/A'))],
            ]
            stats_table = Table(stats_rows, colWidths=[180, 300])
            stats_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), self.zps_blue),
                ('TEXTCOLOR', (0, 0), (0, -1), colors.white),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTNAME', (1, 0), (1, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ]))
            elements.append(stats_table)

            # Case type breakdown
            type_breakdown = case_stats.get('type_breakdown', {})
            if type_breakdown:
                elements.append(Spacer(1, 10))
                elements.append(Paragraph('<b>Case Type Breakdown:</b>', self.styles['BodyText']))
                type_table_data = [['Case Type', 'Count', 'Percentage']]
                for case_type, details in type_breakdown.items():
                    if isinstance(details, dict):
                        type_table_data.append([
                            str(case_type),
                            str(details.get('count', 'N/A')),
                            str(details.get('percentage', 'N/A')),
                        ])
                    else:
                        type_table_data.append([str(case_type), str(details), 'N/A'])

                if len(type_table_data) > 1:
                    type_table = Table(type_table_data, colWidths=[200, 100, 100])
                    type_table.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), self.zps_green),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                        ('FONTSIZE', (0, 0), (-1, -1), 9),
                        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                        ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
                        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.Color(0.95, 0.95, 0.95)]),
                    ]))
                    elements.append(type_table)
        else:
            elements.append(Paragraph('No case statistics available.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- Investigation Statistics ---
        elements.append(Paragraph('<b>INVESTIGATION STATISTICS</b>', self.styles['SectionHeader']))

        inv_stats = self.data.get('investigation_statistics', {})
        if inv_stats:
            inv_rows = [
                ['Total Investigations:', str(inv_stats.get('total_investigations', 'N/A'))],
                ['Completed:', str(inv_stats.get('completed', 'N/A'))],
                ['In Progress:', str(inv_stats.get('in_progress', 'N/A'))],
                ['Failed:', str(inv_stats.get('failed', 'N/A'))],
                ['Average Execution Time:', str(inv_stats.get('avg_execution_time', 'N/A'))],
                ['Most Common Type:', str(inv_stats.get('most_common_type', 'N/A'))],
                ['Success Rate:', str(inv_stats.get('success_rate', 'N/A'))],
                ['Investigations This Month:', str(inv_stats.get('this_month', 'N/A'))],
            ]
            inv_table = Table(inv_rows, colWidths=[180, 300])
            inv_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ]))
            elements.append(inv_table)

            # Investigation type breakdown
            inv_breakdown = inv_stats.get('type_breakdown', {})
            if inv_breakdown:
                elements.append(Spacer(1, 10))
                elements.append(Paragraph('<b>Investigation Type Breakdown:</b>', self.styles['BodyText']))
                inv_type_data = [['Investigation Type', 'Count', 'Avg Time']]
                for inv_type, details in inv_breakdown.items():
                    if isinstance(details, dict):
                        inv_type_data.append([
                            str(inv_type),
                            str(details.get('count', 'N/A')),
                            str(details.get('avg_time', 'N/A')),
                        ])
                    else:
                        inv_type_data.append([str(inv_type), str(details), 'N/A'])

                if len(inv_type_data) > 1:
                    inv_type_table = Table(inv_type_data, colWidths=[200, 100, 100])
                    inv_type_table.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), self.zps_blue),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                        ('FONTSIZE', (0, 0), (-1, -1), 9),
                        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                        ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
                        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.Color(0.95, 0.95, 0.95)]),
                    ]))
                    elements.append(inv_type_table)
        else:
            elements.append(Paragraph('No investigation statistics available.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- Financial Loss Summary ---
        elements.append(Paragraph('<b>FINANCIAL LOSS SUMMARY</b>', self.styles['SectionHeader']))

        financial = self.data.get('financial_summary', {})
        if financial:
            fin_rows = [
                ['Total Reported Losses (ZMW):', str(financial.get('total_losses_zmw', 'N/A'))],
                ['Total Reported Losses (USD):', str(financial.get('total_losses_usd', 'N/A'))],
                ['Total Recovered (ZMW):', str(financial.get('total_recovered_zmw', 'N/A'))],
                ['Recovery Rate:', str(financial.get('recovery_rate', 'N/A'))],
                ['Average Loss per Case:', str(financial.get('avg_loss_per_case', 'N/A'))],
                ['Largest Single Loss:', str(financial.get('largest_loss', 'N/A'))],
                ['Most Common Fraud Type:', str(financial.get('most_common_fraud', 'N/A'))],
                ['Losses This Month:', str(financial.get('losses_this_month', 'N/A'))],
            ]
            fin_table = Table(fin_rows, colWidths=[200, 280])
            fin_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), self.zps_blue),
                ('TEXTCOLOR', (0, 0), (0, -1), colors.white),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTNAME', (1, 0), (1, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ]))
            elements.append(fin_table)

            # Loss by category
            loss_breakdown = financial.get('loss_by_category', {})
            if loss_breakdown:
                elements.append(Spacer(1, 10))
                elements.append(Paragraph('<b>Loss by Category:</b>', self.styles['BodyText']))
                loss_data = [['Category', 'Amount (ZMW)', 'Cases']]
                for category, details in loss_breakdown.items():
                    if isinstance(details, dict):
                        loss_data.append([
                            str(category),
                            str(details.get('amount', 'N/A')),
                            str(details.get('cases', 'N/A')),
                        ])
                    else:
                        loss_data.append([str(category), str(details), 'N/A'])

                if len(loss_data) > 1:
                    loss_table = Table(loss_data, colWidths=[200, 120, 80])
                    loss_table.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), self.zps_green),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                        ('FONTSIZE', (0, 0), (-1, -1), 9),
                        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                        ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
                        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.Color(0.95, 0.95, 0.95)]),
                    ]))
                    elements.append(loss_table)
        else:
            elements.append(Paragraph('No financial loss data available.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- Performance Metrics ---
        elements.append(Paragraph('<b>PERFORMANCE METRICS</b>', self.styles['SectionHeader']))

        metrics = self.data.get('performance_metrics', {})
        if metrics:
            metrics_table_data = [['Metric', 'Value', 'Target', 'Status']]

            metric_items = metrics.get('items', [])
            if metric_items:
                for item in metric_items:
                    status = str(item.get('status', 'N/A'))
                    metrics_table_data.append([
                        str(item.get('name', 'N/A')),
                        str(item.get('value', 'N/A')),
                        str(item.get('target', 'N/A')),
                        status,
                    ])
            else:
                # Fallback: treat metrics dict as key-value pairs
                for key, value in metrics.items():
                    if key != 'items':
                        display_key = str(key).replace('_', ' ').title()
                        metrics_table_data.append([display_key, str(value), 'N/A', 'N/A'])

            if len(metrics_table_data) > 1:
                perf_table = Table(metrics_table_data, colWidths=[180, 100, 100, 80])
                perf_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), self.zps_blue),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 9),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                    ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
                    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.Color(0.95, 0.95, 0.95)]),
                ]))
                elements.append(perf_table)
            else:
                elements.append(Paragraph('No performance metrics data available.', self.styles['BodyText']))

            summary = metrics.get('summary', '')
            if summary:
                elements.append(Spacer(1, 8))
                elements.append(Paragraph(
                    f'<i>Performance Summary: {summary}</i>',
                    self.styles['BodyText']
                ))
        else:
            elements.append(Paragraph('No performance metrics available.', self.styles['BodyText']))
