"""
Cross-Case Correlation PDF Report Generator
CyberTrace - Zambia Police Service

Generate professional court-ready cross-case correlation reports
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime
import os


class CorrelationPDFReport:
    """Generate PDF reports for cross-case correlation analysis"""

    def __init__(self, data, case, investigator, logo_path=None):
        """
        Initialize PDF report generator

        Args:
            data: Dictionary containing cross-case correlation results
            case: Case model instance
            investigator: User model instance (investigator)
            logo_path: Path to police logo image
        """
        self.data = data
        self.case = case
        self.investigator = investigator
        self.logo_path = logo_path or 'app/static/img/zp_logo.jpg'
        self.styles = getSampleStyleSheet()
        self.zps_blue = colors.HexColor('#000663')
        self.zps_green = colors.HexColor('#008000')
        self._create_custom_styles()

    def _create_custom_styles(self):
        """Create custom paragraph styles for the report"""
        self.styles.add(ParagraphStyle(
            name='ReportTitle',
            parent=self.styles['Heading1'],
            fontSize=18,
            textColor=self.zps_blue,
            spaceAfter=12,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=self.zps_blue,
            spaceBefore=12,
            spaceAfter=6,
            fontName='Helvetica-Bold'
        ))
        self.styles.add(ParagraphStyle(
            name='BodyText',
            parent=self.styles['Normal'],
            fontSize=10,
            spaceAfter=6
        ))

    def generate(self, pdf_path):
        """Generate the PDF report at the specified path"""
        doc = SimpleDocTemplate(
            pdf_path,
            pagesize=A4,
            rightMargin=50,
            leftMargin=50,
            topMargin=50,
            bottomMargin=50
        )
        elements = []

        # Header
        elements.append(Paragraph('ZAMBIA POLICE SERVICE', self.styles['ReportTitle']))
        elements.append(Paragraph(
            'CONFIDENTIAL - AUTHORIZED USE ONLY',
            ParagraphStyle(
                name='Watermark',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.red,
                alignment=TA_CENTER
            )
        ))
        elements.append(Spacer(1, 12))

        # Case info table
        case_data = [
            ['Case Number:', self.case.case_number if hasattr(self.case, 'case_number') else str(self.case)],
            ['Investigator:', self.investigator.full_name if hasattr(self.investigator, 'full_name') else str(self.investigator)],
            ['Date:', datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')],
        ]
        t = Table(case_data, colWidths=[120, 350])
        t.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 20))

        # Report-specific content
        self._add_content(elements)

        # Footer
        elements.append(Spacer(1, 30))
        elements.append(Paragraph(
            'This report is generated by CyberTrace OSINT Platform for the Zambia Police Service.',
            ParagraphStyle(
                name='Footer',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.grey
            )
        ))

        doc.build(elements)

    def _add_content(self, elements):
        """Add cross-case correlation content to the report"""

        # Report title
        elements.append(Paragraph(
            '<b>Cross-Case Correlation Report</b>',
            self.styles['ReportTitle']
        ))
        elements.append(Spacer(1, 12))

        # --- Matched Indicators ---
        elements.append(Paragraph('<b>MATCHED INDICATORS</b>', self.styles['SectionHeader']))

        indicators = self.data.get('matched_indicators', [])
        if indicators:
            ind_table_data = [['#', 'Indicator Type', 'Value', 'Cases Matched', 'First Seen', 'Last Seen']]
            for idx, ind in enumerate(indicators, 1):
                value = str(ind.get('value', 'N/A'))
                if len(value) > 30:
                    value = value[:27] + '...'
                ind_table_data.append([
                    str(idx),
                    str(ind.get('type', 'N/A')),
                    value,
                    str(ind.get('cases_matched', 'N/A')),
                    str(ind.get('first_seen', 'N/A')),
                    str(ind.get('last_seen', 'N/A')),
                ])

            ind_table = Table(ind_table_data, colWidths=[25, 80, 145, 70, 75, 75])
            ind_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.zps_blue),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('ALIGN', (0, 0), (0, -1), 'CENTER'),
                ('ALIGN', (3, 0), (3, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.Color(0.95, 0.95, 0.95)]),
            ]))
            elements.append(ind_table)
            elements.append(Paragraph(
                f'Total matched indicators: {len(indicators)}',
                self.styles['BodyText']
            ))
        else:
            elements.append(Paragraph('No matched indicators found across cases.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- Linked Cases Summary ---
        elements.append(Paragraph('<b>LINKED CASES SUMMARY</b>', self.styles['SectionHeader']))

        linked_cases = self.data.get('linked_cases', [])
        if linked_cases:
            case_table_data = [['Case Number', 'Title', 'Status', 'Shared Indicators', 'Correlation Strength']]
            for lc in linked_cases:
                case_table_data.append([
                    str(lc.get('case_number', 'N/A')),
                    str(lc.get('title', 'N/A'))[:35],
                    str(lc.get('status', 'N/A')),
                    str(lc.get('shared_indicators', 'N/A')),
                    str(lc.get('correlation_strength', 'N/A')),
                ])

            case_table = Table(case_table_data, colWidths=[80, 150, 70, 85, 90])
            case_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.zps_green),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('ALIGN', (2, 0), (4, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.Color(0.95, 0.95, 0.95)]),
            ]))
            elements.append(case_table)
            elements.append(Paragraph(
                f'Total linked cases: {len(linked_cases)}',
                self.styles['BodyText']
            ))
        else:
            elements.append(Paragraph('No linked cases identified.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- Threat Actor Profiles ---
        elements.append(Paragraph('<b>THREAT ACTOR PROFILES</b>', self.styles['SectionHeader']))

        threat_actors = self.data.get('threat_actors', [])
        if threat_actors:
            for idx, actor in enumerate(threat_actors, 1):
                elements.append(Paragraph(
                    f'<b>Threat Actor #{idx}: {actor.get("name", actor.get("alias", "Unknown"))}</b>',
                    self.styles['SectionHeader']
                ))

                actor_rows = [
                    ['Alias/Name:', str(actor.get('name', actor.get('alias', 'N/A')))],
                    ['Known Identifiers:', str(actor.get('identifiers', 'N/A'))],
                    ['Associated Cases:', str(actor.get('associated_cases', 'N/A'))],
                    ['Modus Operandi:', str(actor.get('modus_operandi', 'N/A'))],
                    ['Threat Level:', str(actor.get('threat_level', 'N/A'))],
                    ['First Activity:', str(actor.get('first_activity', 'N/A'))],
                    ['Last Activity:', str(actor.get('last_activity', 'N/A'))],
                    ['Notes:', str(actor.get('notes', 'N/A'))],
                ]
                actor_table = Table(actor_rows, colWidths=[140, 340])
                actor_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
                    ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 9),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                    ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ]))
                elements.append(actor_table)
                elements.append(Spacer(1, 8))
        else:
            elements.append(Paragraph('No threat actor profiles identified.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- Confidence Scores ---
        elements.append(Paragraph('<b>CONFIDENCE SCORES</b>', self.styles['SectionHeader']))

        confidence = self.data.get('confidence_scores', {})
        if confidence:
            conf_rows = [
                ['Overall Correlation Confidence:', str(confidence.get('overall', 'N/A'))],
                ['Indicator Match Score:', str(confidence.get('indicator_match', 'N/A'))],
                ['Temporal Correlation:', str(confidence.get('temporal', 'N/A'))],
                ['Behavioral Similarity:', str(confidence.get('behavioral', 'N/A'))],
                ['Geographic Overlap:', str(confidence.get('geographic', 'N/A'))],
                ['Methodology:', str(confidence.get('methodology', 'N/A'))],
            ]
            conf_table = Table(conf_rows, colWidths=[200, 280])
            conf_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), self.zps_blue),
                ('TEXTCOLOR', (0, 0), (0, -1), colors.white),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTNAME', (1, 0), (1, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ]))
            elements.append(conf_table)

            notes = confidence.get('notes', '')
            if notes:
                elements.append(Spacer(1, 8))
                elements.append(Paragraph(
                    f'<i>Analysis Notes: {notes}</i>',
                    self.styles['BodyText']
                ))
        else:
            elements.append(Paragraph('No confidence score data available.', self.styles['BodyText']))
