"""
Cryptocurrency Wallet Investigation PDF Report Generator
CyberTrace - Zambia Police Service

Generate professional court-ready cryptocurrency investigation reports
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime
import os


class CryptoPDFReport:
    """Generate PDF reports for cryptocurrency wallet investigations"""

    def __init__(self, data, case, investigator, logo_path=None):
        """
        Initialize PDF report generator

        Args:
            data: Dictionary containing cryptocurrency investigation results
            case: Case model instance
            investigator: User model instance (investigator)
            logo_path: Path to police logo image
        """
        self.data = data
        self.case = case
        self.investigator = investigator
        self.logo_path = logo_path or 'app/static/img/zp_logo.jpg'
        self.styles = getSampleStyleSheet()
        self.zps_blue = colors.HexColor('#000663')
        self.zps_green = colors.HexColor('#008000')
        self._create_custom_styles()

    def _create_custom_styles(self):
        """Create custom paragraph styles for the report"""
        self.styles.add(ParagraphStyle(
            name='ReportTitle',
            parent=self.styles['Heading1'],
            fontSize=18,
            textColor=self.zps_blue,
            spaceAfter=12,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=self.zps_blue,
            spaceBefore=12,
            spaceAfter=6,
            fontName='Helvetica-Bold'
        ))
        self.styles.add(ParagraphStyle(
            name='BodyText',
            parent=self.styles['Normal'],
            fontSize=10,
            spaceAfter=6
        ))

    def generate(self, pdf_path):
        """Generate the PDF report at the specified path"""
        doc = SimpleDocTemplate(
            pdf_path,
            pagesize=A4,
            rightMargin=50,
            leftMargin=50,
            topMargin=50,
            bottomMargin=50
        )
        elements = []

        # Header
        elements.append(Paragraph('ZAMBIA POLICE SERVICE', self.styles['ReportTitle']))
        elements.append(Paragraph(
            'CONFIDENTIAL - AUTHORIZED USE ONLY',
            ParagraphStyle(
                name='Watermark',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.red,
                alignment=TA_CENTER
            )
        ))
        elements.append(Spacer(1, 12))

        # Case info table
        case_data = [
            ['Case Number:', self.case.case_number if hasattr(self.case, 'case_number') else str(self.case)],
            ['Investigator:', self.investigator.full_name if hasattr(self.investigator, 'full_name') else str(self.investigator)],
            ['Date:', datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')],
        ]
        t = Table(case_data, colWidths=[120, 350])
        t.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 20))

        # Report-specific content
        self._add_content(elements)

        # Footer
        elements.append(Spacer(1, 30))
        elements.append(Paragraph(
            'This report is generated by CyberTrace OSINT Platform for the Zambia Police Service.',
            ParagraphStyle(
                name='Footer',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.grey
            )
        ))

        doc.build(elements)

    def _add_content(self, elements):
        """Add cryptocurrency wallet investigation content to the report"""

        # Report title
        elements.append(Paragraph(
            '<b>Cryptocurrency Wallet Investigation Report</b>',
            self.styles['ReportTitle']
        ))
        elements.append(Spacer(1, 12))

        # --- Wallet Summary ---
        elements.append(Paragraph('<b>WALLET SUMMARY</b>', self.styles['SectionHeader']))

        wallet = self.data.get('wallet', {})
        if wallet:
            wallet_rows = [
                ['Wallet Address:', str(wallet.get('address', 'N/A'))],
                ['Blockchain:', str(wallet.get('chain', wallet.get('blockchain', 'N/A')))],
                ['Balance:', str(wallet.get('balance', 'N/A'))],
                ['Balance (USD):', str(wallet.get('balance_usd', 'N/A'))],
                ['First Transaction:', str(wallet.get('first_transaction', 'N/A'))],
                ['Last Transaction:', str(wallet.get('last_transaction', 'N/A'))],
                ['Total Transactions:', str(wallet.get('total_transactions', 'N/A'))],
                ['Wallet Type:', str(wallet.get('wallet_type', 'N/A'))],
                ['Label/Tag:', str(wallet.get('label', 'N/A'))],
            ]
            wallet_table = Table(wallet_rows, colWidths=[140, 340])
            wallet_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), self.zps_blue),
                ('TEXTCOLOR', (0, 0), (0, -1), colors.white),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ]))
            elements.append(wallet_table)
        else:
            elements.append(Paragraph('No wallet data available.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- Transaction History ---
        elements.append(Paragraph('<b>TRANSACTION HISTORY</b>', self.styles['SectionHeader']))

        transactions = self.data.get('transactions', [])
        if transactions:
            txn_table_data = [['Date', 'TX Hash', 'Type', 'Amount', 'From/To']]
            for txn in transactions:
                tx_hash = str(txn.get('hash', 'N/A'))
                if len(tx_hash) > 16:
                    tx_hash = tx_hash[:8] + '...' + tx_hash[-8:]
                counterparty = str(txn.get('counterparty', txn.get('from', txn.get('to', 'N/A'))))
                if len(counterparty) > 20:
                    counterparty = counterparty[:10] + '...' + counterparty[-8:]
                txn_table_data.append([
                    str(txn.get('date', 'N/A')),
                    tx_hash,
                    str(txn.get('type', 'N/A')),
                    str(txn.get('amount', 'N/A')),
                    counterparty,
                ])

            txn_table = Table(txn_table_data, colWidths=[75, 110, 60, 90, 130])
            txn_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.zps_blue),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 7),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.Color(0.95, 0.95, 0.95)]),
            ]))
            elements.append(txn_table)
            elements.append(Paragraph(
                f'Showing {len(transactions)} transaction(s).',
                self.styles['BodyText']
            ))
        else:
            elements.append(Paragraph('No transaction history available.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- Exchange Identification ---
        elements.append(Paragraph('<b>EXCHANGE IDENTIFICATION</b>', self.styles['SectionHeader']))

        exchanges = self.data.get('exchanges', [])
        if exchanges:
            for idx, exchange in enumerate(exchanges, 1):
                elements.append(Paragraph(
                    f'<b>Exchange #{idx}:</b> {exchange.get("name", "N/A")} - '
                    f'Address: {exchange.get("address", "N/A")} - '
                    f'Confidence: {exchange.get("confidence", "N/A")}',
                    self.styles['BodyText']
                ))
        else:
            elements.append(Paragraph('No exchanges identified in transaction flow.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- Risk Assessment ---
        elements.append(Paragraph('<b>RISK ASSESSMENT</b>', self.styles['SectionHeader']))

        risk = self.data.get('risk_assessment', {})
        if risk:
            risk_score = risk.get('risk_score', 0)
            if risk_score >= 70:
                risk_color = colors.red
            elif risk_score >= 40:
                risk_color = colors.orange
            else:
                risk_color = colors.green

            risk_rows = [
                ['Risk Score:', f'{risk_score}/100'],
                ['Risk Level:', str(risk.get('risk_level', 'N/A'))],
                ['Darknet Exposure:', str(risk.get('darknet_exposure', 'N/A'))],
                ['Sanctions Match:', str(risk.get('sanctions_match', 'N/A'))],
                ['Mixer/Tumbler Usage:', str(risk.get('mixer_usage', 'N/A'))],
                ['Gambling Association:', str(risk.get('gambling', 'N/A'))],
            ]
            risk_table = Table(risk_rows, colWidths=[160, 320])
            risk_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('TEXTCOLOR', (1, 0), (1, 0), risk_color),
                ('FONTNAME', (1, 0), (1, 0), 'Helvetica-Bold'),
            ]))
            elements.append(risk_table)

            # Risk flags
            flags = risk.get('flags', [])
            if flags:
                elements.append(Spacer(1, 8))
                elements.append(Paragraph('<b>Risk Flags:</b>', self.styles['BodyText']))
                for flag in flags:
                    elements.append(Paragraph(f'  - {flag}', self.styles['BodyText']))
        else:
            elements.append(Paragraph('No risk assessment data available.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- Connected Wallets ---
        elements.append(Paragraph('<b>CONNECTED WALLETS</b>', self.styles['SectionHeader']))

        connected = self.data.get('connected_wallets', [])
        if connected:
            conn_table_data = [['#', 'Wallet Address', 'Blockchain', 'Relationship', 'Transactions']]
            for idx, cw in enumerate(connected, 1):
                addr = str(cw.get('address', 'N/A'))
                if len(addr) > 24:
                    addr = addr[:12] + '...' + addr[-10:]
                conn_table_data.append([
                    str(idx),
                    addr,
                    str(cw.get('chain', 'N/A')),
                    str(cw.get('relationship', 'N/A')),
                    str(cw.get('transaction_count', 'N/A')),
                ])

            conn_table = Table(conn_table_data, colWidths=[30, 170, 80, 100, 80])
            conn_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.zps_green),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('ALIGN', (0, 0), (0, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ]))
            elements.append(conn_table)
            elements.append(Paragraph(
                f'Total connected wallets identified: {len(connected)}',
                self.styles['BodyText']
            ))
        else:
            elements.append(Paragraph('No connected wallets identified.', self.styles['BodyText']))
