"""
Domain/IP Investigation PDF Report Generator
CyberTrace - Zambia Police Service

Generate professional court-ready domain and IP investigation reports
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime
import os


class DomainIPPDFReport:
    """Generate PDF reports for domain and IP investigations"""

    def __init__(self, data, case, investigator, logo_path=None):
        """
        Initialize PDF report generator

        Args:
            data: Dictionary containing domain/IP investigation results
            case: Case model instance
            investigator: User model instance (investigator)
            logo_path: Path to police logo image
        """
        self.data = data
        self.case = case
        self.investigator = investigator
        self.logo_path = logo_path or 'app/static/img/zp_logo.jpg'
        self.styles = getSampleStyleSheet()
        self.zps_blue = colors.HexColor('#000663')
        self.zps_green = colors.HexColor('#008000')
        self._create_custom_styles()

    def _create_custom_styles(self):
        """Create custom paragraph styles for the report"""
        self.styles.add(ParagraphStyle(
            name='ReportTitle',
            parent=self.styles['Heading1'],
            fontSize=18,
            textColor=self.zps_blue,
            spaceAfter=12,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=self.zps_blue,
            spaceBefore=12,
            spaceAfter=6,
            fontName='Helvetica-Bold'
        ))
        self.styles.add(ParagraphStyle(
            name='BodyText',
            parent=self.styles['Normal'],
            fontSize=10,
            spaceAfter=6
        ))

    def generate(self, pdf_path):
        """Generate the PDF report at the specified path"""
        doc = SimpleDocTemplate(
            pdf_path,
            pagesize=A4,
            rightMargin=50,
            leftMargin=50,
            topMargin=50,
            bottomMargin=50
        )
        elements = []

        # Header
        elements.append(Paragraph('ZAMBIA POLICE SERVICE', self.styles['ReportTitle']))
        elements.append(Paragraph(
            'CONFIDENTIAL - AUTHORIZED USE ONLY',
            ParagraphStyle(
                name='Watermark',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.red,
                alignment=TA_CENTER
            )
        ))
        elements.append(Spacer(1, 12))

        # Case info table
        case_data = [
            ['Case Number:', self.case.case_number if hasattr(self.case, 'case_number') else str(self.case)],
            ['Investigator:', self.investigator.full_name if hasattr(self.investigator, 'full_name') else str(self.investigator)],
            ['Date:', datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')],
        ]
        t = Table(case_data, colWidths=[120, 350])
        t.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 20))

        # Report-specific content
        self._add_content(elements)

        # Footer
        elements.append(Spacer(1, 30))
        elements.append(Paragraph(
            'This report is generated by CyberTrace OSINT Platform for the Zambia Police Service.',
            ParagraphStyle(
                name='Footer',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.grey
            )
        ))

        doc.build(elements)

    def _add_content(self, elements):
        """Add domain/IP investigation content to the report"""

        # Report title
        elements.append(Paragraph(
            '<b>Domain/IP Investigation Report</b>',
            self.styles['ReportTitle']
        ))
        elements.append(Spacer(1, 12))

        # --- WHOIS Data ---
        elements.append(Paragraph('<b>WHOIS INFORMATION</b>', self.styles['SectionHeader']))

        whois_data = self.data.get('whois', {})
        if whois_data:
            whois_rows = [
                ['Domain/IP:', str(whois_data.get('domain', whois_data.get('ip', 'N/A')))],
                ['Registrar:', str(whois_data.get('registrar', 'N/A'))],
                ['Registrant:', str(whois_data.get('registrant', 'N/A'))],
                ['Organization:', str(whois_data.get('organization', 'N/A'))],
                ['Creation Date:', str(whois_data.get('creation_date', 'N/A'))],
                ['Expiration Date:', str(whois_data.get('expiration_date', 'N/A'))],
                ['Updated Date:', str(whois_data.get('updated_date', 'N/A'))],
                ['Country:', str(whois_data.get('country', 'N/A'))],
                ['Name Servers:', str(', '.join(whois_data.get('name_servers', [])) if whois_data.get('name_servers') else 'N/A')],
            ]
            whois_table = Table(whois_rows, colWidths=[140, 340])
            whois_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ]))
            elements.append(whois_table)
        else:
            elements.append(Paragraph('No WHOIS data available.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- DNS Records ---
        elements.append(Paragraph('<b>DNS RECORDS</b>', self.styles['SectionHeader']))

        dns_records = self.data.get('dns_records', {})
        if dns_records:
            dns_table_data = [['Record Type', 'Value', 'TTL']]
            for record_type, records in dns_records.items():
                if isinstance(records, list):
                    for record in records:
                        if isinstance(record, dict):
                            dns_table_data.append([
                                str(record_type).upper(),
                                str(record.get('value', 'N/A')),
                                str(record.get('ttl', 'N/A')),
                            ])
                        else:
                            dns_table_data.append([str(record_type).upper(), str(record), 'N/A'])
                else:
                    dns_table_data.append([str(record_type).upper(), str(records), 'N/A'])

            if len(dns_table_data) > 1:
                dns_table = Table(dns_table_data, colWidths=[100, 300, 80])
                dns_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), self.zps_blue),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 8),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.Color(0.95, 0.95, 0.95)]),
                ]))
                elements.append(dns_table)
            else:
                elements.append(Paragraph('No DNS records found.', self.styles['BodyText']))
        else:
            elements.append(Paragraph('No DNS records available.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- SSL Certificate Info ---
        elements.append(Paragraph('<b>SSL CERTIFICATE INFORMATION</b>', self.styles['SectionHeader']))

        ssl_info = self.data.get('ssl_certificate', {})
        if ssl_info:
            ssl_rows = [
                ['Issuer:', str(ssl_info.get('issuer', 'N/A'))],
                ['Subject:', str(ssl_info.get('subject', 'N/A'))],
                ['Valid From:', str(ssl_info.get('valid_from', 'N/A'))],
                ['Valid Until:', str(ssl_info.get('valid_until', 'N/A'))],
                ['Serial Number:', str(ssl_info.get('serial_number', 'N/A'))],
                ['Signature Algorithm:', str(ssl_info.get('signature_algorithm', 'N/A'))],
                ['Key Size:', str(ssl_info.get('key_size', 'N/A'))],
            ]
            ssl_table = Table(ssl_rows, colWidths=[160, 320])
            ssl_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ]))
            elements.append(ssl_table)
        else:
            elements.append(Paragraph('No SSL certificate data available.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- Subdomains List ---
        elements.append(Paragraph('<b>SUBDOMAINS</b>', self.styles['SectionHeader']))

        subdomains = self.data.get('subdomains', [])
        if subdomains:
            sub_table_data = [['#', 'Subdomain', 'IP Address', 'Status']]
            for idx, sub in enumerate(subdomains, 1):
                if isinstance(sub, dict):
                    sub_table_data.append([
                        str(idx),
                        str(sub.get('subdomain', 'N/A')),
                        str(sub.get('ip', 'N/A')),
                        str(sub.get('status', 'N/A')),
                    ])
                else:
                    sub_table_data.append([str(idx), str(sub), 'N/A', 'N/A'])

            sub_table = Table(sub_table_data, colWidths=[30, 200, 120, 80])
            sub_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.zps_green),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('ALIGN', (0, 0), (0, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ]))
            elements.append(sub_table)
            elements.append(Paragraph(
                f'Total subdomains discovered: {len(subdomains)}',
                self.styles['BodyText']
            ))
        else:
            elements.append(Paragraph('No subdomains discovered.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- IP Geolocation ---
        elements.append(Paragraph('<b>IP GEOLOCATION</b>', self.styles['SectionHeader']))

        geolocation = self.data.get('geolocation', {})
        if geolocation:
            geo_rows = [
                ['IP Address:', str(geolocation.get('ip', 'N/A'))],
                ['Country:', str(geolocation.get('country', 'N/A'))],
                ['Region:', str(geolocation.get('region', 'N/A'))],
                ['City:', str(geolocation.get('city', 'N/A'))],
                ['Latitude:', str(geolocation.get('latitude', 'N/A'))],
                ['Longitude:', str(geolocation.get('longitude', 'N/A'))],
                ['ISP:', str(geolocation.get('isp', 'N/A'))],
                ['ASN:', str(geolocation.get('asn', 'N/A'))],
                ['Organization:', str(geolocation.get('organization', 'N/A'))],
            ]
            geo_table = Table(geo_rows, colWidths=[140, 340])
            geo_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ]))
            elements.append(geo_table)
        else:
            elements.append(Paragraph('No geolocation data available.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- Reputation Scores ---
        elements.append(Paragraph('<b>REPUTATION SCORES</b>', self.styles['SectionHeader']))

        reputation = self.data.get('reputation', {})
        if reputation:
            rep_rows = [
                ['Overall Score:', str(reputation.get('overall_score', 'N/A'))],
                ['Malware Association:', str(reputation.get('malware', 'N/A'))],
                ['Phishing Association:', str(reputation.get('phishing', 'N/A'))],
                ['Spam Association:', str(reputation.get('spam', 'N/A'))],
                ['Blacklist Status:', str(reputation.get('blacklist_status', 'N/A'))],
                ['Threat Level:', str(reputation.get('threat_level', 'N/A'))],
                ['Last Seen Malicious:', str(reputation.get('last_seen_malicious', 'N/A'))],
            ]
            rep_table = Table(rep_rows, colWidths=[160, 320])
            rep_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), self.zps_blue),
                ('TEXTCOLOR', (0, 0), (0, -1), colors.white),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ]))
            elements.append(rep_table)
        else:
            elements.append(Paragraph('No reputation data available.', self.styles['BodyText']))
