"""
Financial Transaction Analysis PDF Report Generator
CyberTrace - Zambia Police Service

Generate professional court-ready financial investigation reports
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime
import os


class FinancialPDFReport:
    """Generate PDF reports for financial transaction analysis investigations"""

    def __init__(self, data, case, investigator, logo_path=None):
        """
        Initialize PDF report generator

        Args:
            data: Dictionary containing financial investigation results
            case: Case model instance
            investigator: User model instance (investigator)
            logo_path: Path to police logo image
        """
        self.data = data
        self.case = case
        self.investigator = investigator
        self.logo_path = logo_path or 'app/static/img/zp_logo.jpg'
        self.styles = getSampleStyleSheet()
        self.zps_blue = colors.HexColor('#000663')
        self.zps_green = colors.HexColor('#008000')
        self._create_custom_styles()

    def _create_custom_styles(self):
        """Create custom paragraph styles for the report"""
        self.styles.add(ParagraphStyle(
            name='ReportTitle',
            parent=self.styles['Heading1'],
            fontSize=18,
            textColor=self.zps_blue,
            spaceAfter=12,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=self.zps_blue,
            spaceBefore=12,
            spaceAfter=6,
            fontName='Helvetica-Bold'
        ))
        self.styles.add(ParagraphStyle(
            name='BodyText',
            parent=self.styles['Normal'],
            fontSize=10,
            spaceAfter=6
        ))

    def generate(self, pdf_path):
        """Generate the PDF report at the specified path"""
        doc = SimpleDocTemplate(
            pdf_path,
            pagesize=A4,
            rightMargin=50,
            leftMargin=50,
            topMargin=50,
            bottomMargin=50
        )
        elements = []

        # Header
        elements.append(Paragraph('ZAMBIA POLICE SERVICE', self.styles['ReportTitle']))
        elements.append(Paragraph(
            'CONFIDENTIAL - AUTHORIZED USE ONLY',
            ParagraphStyle(
                name='Watermark',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.red,
                alignment=TA_CENTER
            )
        ))
        elements.append(Spacer(1, 12))

        # Case info table
        case_data = [
            ['Case Number:', self.case.case_number if hasattr(self.case, 'case_number') else str(self.case)],
            ['Investigator:', self.investigator.full_name if hasattr(self.investigator, 'full_name') else str(self.investigator)],
            ['Date:', datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')],
        ]
        t = Table(case_data, colWidths=[120, 350])
        t.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 20))

        # Report-specific content
        self._add_content(elements)

        # Footer
        elements.append(Spacer(1, 30))
        elements.append(Paragraph(
            'This report is generated by CyberTrace OSINT Platform for the Zambia Police Service.',
            ParagraphStyle(
                name='Footer',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.grey
            )
        ))

        doc.build(elements)

    def _add_content(self, elements):
        """Add financial transaction analysis content to the report"""

        # Report title
        elements.append(Paragraph(
            '<b>Financial Transaction Analysis Report</b>',
            self.styles['ReportTitle']
        ))
        elements.append(Spacer(1, 12))

        # --- Transaction Summary ---
        elements.append(Paragraph('<b>TRANSACTION SUMMARY</b>', self.styles['SectionHeader']))

        transactions = self.data.get('transactions', [])
        if transactions:
            table_data = [['Date', 'Reference', 'From Account', 'To Account', 'Amount', 'Currency']]
            for txn in transactions:
                table_data.append([
                    str(txn.get('date', 'N/A')),
                    str(txn.get('reference', 'N/A')),
                    str(txn.get('from_account', 'N/A')),
                    str(txn.get('to_account', 'N/A')),
                    str(txn.get('amount', 'N/A')),
                    str(txn.get('currency', 'ZMW')),
                ])

            txn_table = Table(table_data, colWidths=[70, 80, 85, 85, 75, 55])
            txn_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.zps_blue),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('ALIGN', (4, 1), (4, -1), 'RIGHT'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.Color(0.95, 0.95, 0.95)]),
            ]))
            elements.append(txn_table)
        else:
            elements.append(Paragraph('No transaction data available.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- Mule Account Alerts ---
        elements.append(Paragraph('<b>MULE ACCOUNT ALERTS</b>', self.styles['SectionHeader']))

        mule_alerts = self.data.get('mule_accounts', [])
        if mule_alerts:
            for idx, alert in enumerate(mule_alerts, 1):
                account = alert.get('account_number', 'N/A')
                holder = alert.get('account_holder', 'N/A')
                reason = alert.get('reason', 'N/A')
                risk_level = alert.get('risk_level', 'N/A')
                elements.append(Paragraph(
                    f'<b>Alert #{idx}:</b> Account {account} ({holder}) - '
                    f'Risk: <font color="red">{risk_level}</font> - {reason}',
                    self.styles['BodyText']
                ))
        else:
            elements.append(Paragraph(
                '<font color="green">No mule account alerts identified.</font>',
                self.styles['BodyText']
            ))

        elements.append(Spacer(1, 16))

        # --- Flow Analysis Summary ---
        elements.append(Paragraph('<b>FLOW ANALYSIS SUMMARY</b>', self.styles['SectionHeader']))

        flow_analysis = self.data.get('flow_analysis', {})
        if flow_analysis:
            flow_data = [
                ['Total Inflows:', str(flow_analysis.get('total_inflows', 'N/A'))],
                ['Total Outflows:', str(flow_analysis.get('total_outflows', 'N/A'))],
                ['Net Flow:', str(flow_analysis.get('net_flow', 'N/A'))],
                ['Unique Senders:', str(flow_analysis.get('unique_senders', 'N/A'))],
                ['Unique Recipients:', str(flow_analysis.get('unique_recipients', 'N/A'))],
                ['Rapid Movement Detected:', 'YES' if flow_analysis.get('rapid_movement') else 'NO'],
                ['Layering Pattern Detected:', 'YES' if flow_analysis.get('layering_detected') else 'NO'],
                ['Structuring Detected:', 'YES' if flow_analysis.get('structuring_detected') else 'NO'],
            ]
            flow_table = Table(flow_data, colWidths=[180, 300])
            flow_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ]))
            elements.append(flow_table)
        else:
            elements.append(Paragraph('No flow analysis data available.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- Total Amounts ---
        elements.append(Paragraph('<b>TOTAL AMOUNTS</b>', self.styles['SectionHeader']))

        totals = self.data.get('totals', {})
        if totals:
            totals_data = [
                ['Total Transaction Count:', str(totals.get('transaction_count', 'N/A'))],
                ['Total Amount (ZMW):', str(totals.get('total_amount_zmw', 'N/A'))],
                ['Total Amount (USD):', str(totals.get('total_amount_usd', 'N/A'))],
                ['Average Transaction:', str(totals.get('average_transaction', 'N/A'))],
                ['Largest Transaction:', str(totals.get('largest_transaction', 'N/A'))],
                ['Smallest Transaction:', str(totals.get('smallest_transaction', 'N/A'))],
                ['Date Range:', str(totals.get('date_range', 'N/A'))],
            ]
            totals_table = Table(totals_data, colWidths=[180, 300])
            totals_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), self.zps_blue),
                ('TEXTCOLOR', (0, 0), (0, -1), colors.white),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTNAME', (1, 0), (1, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ]))
            elements.append(totals_table)
        else:
            elements.append(Paragraph('No total amount data available.', self.styles['BodyText']))
