"""
Digital Forensics Analysis PDF Report Generator
CyberTrace - Zambia Police Service

Generate professional court-ready digital forensics analysis reports
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime
import os


class ForensicsPDFReport:
    """Generate PDF reports for digital forensics analysis"""

    def __init__(self, data, case, investigator, logo_path=None):
        """
        Initialize PDF report generator

        Args:
            data: Dictionary containing digital forensics results
            case: Case model instance
            investigator: User model instance (investigator)
            logo_path: Path to police logo image
        """
        self.data = data
        self.case = case
        self.investigator = investigator
        self.logo_path = logo_path or 'app/static/img/zp_logo.jpg'
        self.styles = getSampleStyleSheet()
        self.zps_blue = colors.HexColor('#000663')
        self.zps_green = colors.HexColor('#008000')
        self._create_custom_styles()

    def _create_custom_styles(self):
        """Create custom paragraph styles for the report"""
        self.styles.add(ParagraphStyle(
            name='ReportTitle',
            parent=self.styles['Heading1'],
            fontSize=18,
            textColor=self.zps_blue,
            spaceAfter=12,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=self.zps_blue,
            spaceBefore=12,
            spaceAfter=6,
            fontName='Helvetica-Bold'
        ))
        self.styles.add(ParagraphStyle(
            name='BodyText',
            parent=self.styles['Normal'],
            fontSize=10,
            spaceAfter=6
        ))

    def generate(self, pdf_path):
        """Generate the PDF report at the specified path"""
        doc = SimpleDocTemplate(
            pdf_path,
            pagesize=A4,
            rightMargin=50,
            leftMargin=50,
            topMargin=50,
            bottomMargin=50
        )
        elements = []

        # Header
        elements.append(Paragraph('ZAMBIA POLICE SERVICE', self.styles['ReportTitle']))
        elements.append(Paragraph(
            'CONFIDENTIAL - AUTHORIZED USE ONLY',
            ParagraphStyle(
                name='Watermark',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.red,
                alignment=TA_CENTER
            )
        ))
        elements.append(Spacer(1, 12))

        # Case info table
        case_data = [
            ['Case Number:', self.case.case_number if hasattr(self.case, 'case_number') else str(self.case)],
            ['Investigator:', self.investigator.full_name if hasattr(self.investigator, 'full_name') else str(self.investigator)],
            ['Date:', datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')],
        ]
        t = Table(case_data, colWidths=[120, 350])
        t.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 20))

        # Report-specific content
        self._add_content(elements)

        # Footer
        elements.append(Spacer(1, 30))
        elements.append(Paragraph(
            'This report is generated by CyberTrace OSINT Platform for the Zambia Police Service.',
            ParagraphStyle(
                name='Footer',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.grey
            )
        ))

        doc.build(elements)

    def _add_content(self, elements):
        """Add digital forensics analysis content to the report"""

        # Report title
        elements.append(Paragraph(
            '<b>Digital Forensics Analysis Report</b>',
            self.styles['ReportTitle']
        ))
        elements.append(Spacer(1, 12))

        # --- File Information ---
        elements.append(Paragraph('<b>FILE INFORMATION</b>', self.styles['SectionHeader']))

        file_info = self.data.get('file_info', {})
        if file_info:
            file_rows = [
                ['File Name:', str(file_info.get('name', 'N/A'))],
                ['File Size:', str(file_info.get('size', 'N/A'))],
                ['File Type:', str(file_info.get('file_type', file_info.get('mime_type', 'N/A')))],
                ['MD5 Hash:', str(file_info.get('md5', 'N/A'))],
                ['SHA-1 Hash:', str(file_info.get('sha1', 'N/A'))],
                ['SHA-256 Hash:', str(file_info.get('sha256', 'N/A'))],
                ['Created:', str(file_info.get('created', 'N/A'))],
                ['Modified:', str(file_info.get('modified', 'N/A'))],
                ['Accessed:', str(file_info.get('accessed', 'N/A'))],
            ]
            file_table = Table(file_rows, colWidths=[120, 360])
            file_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), self.zps_blue),
                ('TEXTCOLOR', (0, 0), (0, -1), colors.white),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ]))
            elements.append(file_table)
        else:
            elements.append(Paragraph('No file information available.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- EXIF / Metadata ---
        elements.append(Paragraph('<b>EXIF / METADATA</b>', self.styles['SectionHeader']))

        metadata = self.data.get('metadata', self.data.get('exif', {}))
        if metadata:
            meta_table_data = [['Property', 'Value']]
            for key, value in metadata.items():
                display_key = str(key).replace('_', ' ').title()
                display_value = str(value) if value is not None else 'N/A'
                if len(display_value) > 80:
                    display_value = display_value[:77] + '...'
                meta_table_data.append([display_key, display_value])

            if len(meta_table_data) > 1:
                meta_table = Table(meta_table_data, colWidths=[160, 320])
                meta_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), self.zps_blue),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 8),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                    ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.Color(0.95, 0.95, 0.95)]),
                ]))
                elements.append(meta_table)
                elements.append(Paragraph(
                    f'Total metadata properties extracted: {len(meta_table_data) - 1}',
                    self.styles['BodyText']
                ))
            else:
                elements.append(Paragraph('No metadata properties found.', self.styles['BodyText']))
        else:
            elements.append(Paragraph('No EXIF/metadata available.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- GPS Coordinates ---
        elements.append(Paragraph('<b>GPS COORDINATES</b>', self.styles['SectionHeader']))

        gps = self.data.get('gps', self.data.get('gps_coordinates', {}))
        if gps:
            gps_rows = [
                ['Latitude:', str(gps.get('latitude', 'N/A'))],
                ['Longitude:', str(gps.get('longitude', 'N/A'))],
                ['Altitude:', str(gps.get('altitude', 'N/A'))],
                ['GPS Timestamp:', str(gps.get('timestamp', 'N/A'))],
                ['Map Reference:', str(gps.get('map_reference', 'N/A'))],
                ['Location Name:', str(gps.get('location_name', 'N/A'))],
            ]
            gps_table = Table(gps_rows, colWidths=[140, 340])
            gps_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), self.zps_green),
                ('TEXTCOLOR', (0, 0), (0, -1), colors.white),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ]))
            elements.append(gps_table)

            if gps.get('latitude') and gps.get('longitude'):
                elements.append(Paragraph(
                    f'<i>GPS coordinates indicate the file was created or modified at '
                    f'latitude {gps.get("latitude")}, longitude {gps.get("longitude")}.</i>',
                    self.styles['BodyText']
                ))
        else:
            elements.append(Paragraph('No GPS coordinate data found in the file.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- Manipulation Analysis ---
        elements.append(Paragraph('<b>MANIPULATION ANALYSIS</b>', self.styles['SectionHeader']))

        manipulation = self.data.get('manipulation_analysis', {})
        if manipulation:
            manip_rows = [
                ['Manipulation Detected:', 'YES' if manipulation.get('is_manipulated') else 'NO'],
                ['Confidence:', str(manipulation.get('confidence', 'N/A'))],
                ['Software Used:', str(manipulation.get('software', 'N/A'))],
                ['Edit Count:', str(manipulation.get('edit_count', 'N/A'))],
                ['Error Level Analysis:', str(manipulation.get('ela_result', 'N/A'))],
                ['Clone Detection:', str(manipulation.get('clone_detection', 'N/A'))],
            ]
            manip_table = Table(manip_rows, colWidths=[160, 320])
            manip_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ]))
            elements.append(manip_table)

            findings = manipulation.get('findings', [])
            if findings:
                elements.append(Spacer(1, 8))
                elements.append(Paragraph('<b>Detailed Findings:</b>', self.styles['BodyText']))
                for finding in findings:
                    elements.append(Paragraph(f'  - {finding}', self.styles['BodyText']))
        else:
            elements.append(Paragraph('No manipulation analysis data available.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- OCR Text Excerpt ---
        elements.append(Paragraph('<b>OCR TEXT EXCERPT</b>', self.styles['SectionHeader']))

        ocr_text = self.data.get('ocr_text', self.data.get('ocr', ''))
        if ocr_text:
            # Truncate if too long
            display_text = str(ocr_text)
            if len(display_text) > 2000:
                display_text = display_text[:2000] + '\n\n[... Text truncated. Full text available in raw data ...]'

            # Escape special XML characters for ReportLab
            display_text = display_text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')

            elements.append(Paragraph(
                '<b>Extracted Text:</b>',
                self.styles['BodyText']
            ))
            elements.append(Spacer(1, 4))

            # Display in a bordered box
            ocr_data = [[Paragraph(
                f'<font name="Courier" size="8">{display_text}</font>',
                self.styles['BodyText']
            )]]
            ocr_table = Table(ocr_data, colWidths=[470])
            ocr_table.setStyle(TableStyle([
                ('BOX', (0, 0), (-1, -1), 1, colors.grey),
                ('BACKGROUND', (0, 0), (-1, -1), colors.Color(0.97, 0.97, 0.97)),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('LEFTPADDING', (0, 0), (-1, -1), 8),
                ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ]))
            elements.append(ocr_table)

            char_count = len(str(ocr_text))
            elements.append(Paragraph(
                f'Total characters extracted: {char_count}',
                self.styles['BodyText']
            ))
        else:
            elements.append(Paragraph('No OCR text extracted from this file.', self.styles['BodyText']))
