"""
Messaging Forensics PDF Report Generator
CyberTrace - Zambia Police Service

Generate professional court-ready messaging forensics reports
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime
import os


class MessagingPDFReport:
    """Generate PDF reports for messaging forensics investigations"""

    def __init__(self, data, case, investigator, logo_path=None):
        """
        Initialize PDF report generator

        Args:
            data: Dictionary containing messaging forensics results
            case: Case model instance
            investigator: User model instance (investigator)
            logo_path: Path to police logo image
        """
        self.data = data
        self.case = case
        self.investigator = investigator
        self.logo_path = logo_path or 'app/static/img/zp_logo.jpg'
        self.styles = getSampleStyleSheet()
        self.zps_blue = colors.HexColor('#000663')
        self.zps_green = colors.HexColor('#008000')
        self._create_custom_styles()

    def _create_custom_styles(self):
        """Create custom paragraph styles for the report"""
        self.styles.add(ParagraphStyle(
            name='ReportTitle',
            parent=self.styles['Heading1'],
            fontSize=18,
            textColor=self.zps_blue,
            spaceAfter=12,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=self.zps_blue,
            spaceBefore=12,
            spaceAfter=6,
            fontName='Helvetica-Bold'
        ))
        self.styles.add(ParagraphStyle(
            name='BodyText',
            parent=self.styles['Normal'],
            fontSize=10,
            spaceAfter=6
        ))

    def generate(self, pdf_path):
        """Generate the PDF report at the specified path"""
        doc = SimpleDocTemplate(
            pdf_path,
            pagesize=A4,
            rightMargin=50,
            leftMargin=50,
            topMargin=50,
            bottomMargin=50
        )
        elements = []

        # Header
        elements.append(Paragraph('ZAMBIA POLICE SERVICE', self.styles['ReportTitle']))
        elements.append(Paragraph(
            'CONFIDENTIAL - AUTHORIZED USE ONLY',
            ParagraphStyle(
                name='Watermark',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.red,
                alignment=TA_CENTER
            )
        ))
        elements.append(Spacer(1, 12))

        # Case info table
        case_data = [
            ['Case Number:', self.case.case_number if hasattr(self.case, 'case_number') else str(self.case)],
            ['Investigator:', self.investigator.full_name if hasattr(self.investigator, 'full_name') else str(self.investigator)],
            ['Date:', datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')],
        ]
        t = Table(case_data, colWidths=[120, 350])
        t.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 20))

        # Report-specific content
        self._add_content(elements)

        # Footer
        elements.append(Spacer(1, 30))
        elements.append(Paragraph(
            'This report is generated by CyberTrace OSINT Platform for the Zambia Police Service.',
            ParagraphStyle(
                name='Footer',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.grey
            )
        ))

        doc.build(elements)

    def _add_content(self, elements):
        """Add messaging forensics content to the report"""

        # Report title
        elements.append(Paragraph(
            '<b>Messaging Forensics Report</b>',
            self.styles['ReportTitle']
        ))
        elements.append(Spacer(1, 12))

        # --- Chat Statistics ---
        elements.append(Paragraph('<b>CHAT STATISTICS</b>', self.styles['SectionHeader']))

        stats = self.data.get('chat_statistics', {})
        if stats:
            stats_rows = [
                ['Platform:', str(stats.get('platform', 'N/A'))],
                ['Total Messages:', str(stats.get('total_messages', 'N/A'))],
                ['Total Participants:', str(stats.get('total_participants', 'N/A'))],
                ['Date Range:', str(stats.get('date_range', 'N/A'))],
                ['Media Files:', str(stats.get('media_count', 'N/A'))],
                ['Deleted Messages:', str(stats.get('deleted_messages', 'N/A'))],
                ['Average Messages/Day:', str(stats.get('avg_messages_per_day', 'N/A'))],
                ['Peak Activity Time:', str(stats.get('peak_activity_time', 'N/A'))],
                ['Chat Type:', str(stats.get('chat_type', 'N/A'))],
            ]
            stats_table = Table(stats_rows, colWidths=[160, 320])
            stats_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), self.zps_blue),
                ('TEXTCOLOR', (0, 0), (0, -1), colors.white),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ]))
            elements.append(stats_table)
        else:
            elements.append(Paragraph('No chat statistics available.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- Extracted Links ---
        elements.append(Paragraph('<b>EXTRACTED LINKS</b>', self.styles['SectionHeader']))

        links = self.data.get('extracted_links', [])
        if links:
            link_table_data = [['#', 'URL', 'Context', 'Sender', 'Date']]
            for idx, link in enumerate(links, 1):
                url = str(link.get('url', 'N/A'))
                if len(url) > 45:
                    url = url[:42] + '...'
                link_table_data.append([
                    str(idx),
                    url,
                    str(link.get('context', 'N/A'))[:30],
                    str(link.get('sender', 'N/A')),
                    str(link.get('date', 'N/A')),
                ])

            link_table = Table(link_table_data, colWidths=[25, 180, 110, 80, 70])
            link_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.zps_blue),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 7),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('ALIGN', (0, 0), (0, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.Color(0.95, 0.95, 0.95)]),
            ]))
            elements.append(link_table)
            elements.append(Paragraph(
                f'Total links extracted: {len(links)}',
                self.styles['BodyText']
            ))
        else:
            elements.append(Paragraph('No links extracted from messages.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- Extracted Phone Numbers ---
        elements.append(Paragraph('<b>EXTRACTED PHONE NUMBERS</b>', self.styles['SectionHeader']))

        phone_numbers = self.data.get('extracted_phone_numbers', [])
        if phone_numbers:
            phone_table_data = [['#', 'Phone Number', 'Context', 'Sender', 'Frequency']]
            for idx, phone in enumerate(phone_numbers, 1):
                phone_table_data.append([
                    str(idx),
                    str(phone.get('number', 'N/A')),
                    str(phone.get('context', 'N/A'))[:35],
                    str(phone.get('sender', 'N/A')),
                    str(phone.get('frequency', 'N/A')),
                ])

            phone_table = Table(phone_table_data, colWidths=[25, 110, 150, 100, 65])
            phone_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.zps_green),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('ALIGN', (0, 0), (0, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ]))
            elements.append(phone_table)
            elements.append(Paragraph(
                f'Total unique phone numbers extracted: {len(phone_numbers)}',
                self.styles['BodyText']
            ))
        else:
            elements.append(Paragraph('No phone numbers extracted from messages.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- Suspicious Content Flags ---
        elements.append(Paragraph('<b>SUSPICIOUS CONTENT FLAGS</b>', self.styles['SectionHeader']))

        flags = self.data.get('suspicious_flags', [])
        if flags:
            for idx, flag in enumerate(flags, 1):
                severity = flag.get('severity', 'N/A')
                if severity.upper() in ('HIGH', 'CRITICAL'):
                    sev_text = f'<font color="red"><b>{severity}</b></font>'
                elif severity.upper() == 'MEDIUM':
                    sev_text = f'<font color="orange"><b>{severity}</b></font>'
                else:
                    sev_text = f'<b>{severity}</b>'

                elements.append(Paragraph(
                    f'<b>Flag #{idx}:</b> [{sev_text}] {flag.get("description", "N/A")}',
                    self.styles['BodyText']
                ))
                if flag.get('message_excerpt'):
                    elements.append(Paragraph(
                        f'  Excerpt: <i>"{flag.get("message_excerpt")}"</i>',
                        self.styles['BodyText']
                    ))
                if flag.get('sender'):
                    elements.append(Paragraph(
                        f'  Sender: {flag.get("sender")} | Date: {flag.get("date", "N/A")}',
                        self.styles['BodyText']
                    ))
                elements.append(Spacer(1, 4))
        else:
            elements.append(Paragraph(
                '<font color="green">No suspicious content flags identified.</font>',
                self.styles['BodyText']
            ))

        elements.append(Spacer(1, 16))

        # --- Participant Information ---
        elements.append(Paragraph('<b>PARTICIPANT INFORMATION</b>', self.styles['SectionHeader']))

        participants = self.data.get('participants', [])
        if participants:
            part_table_data = [['#', 'Name/Handle', 'Phone/ID', 'Messages Sent', 'Role', 'First Seen']]
            for idx, part in enumerate(participants, 1):
                part_table_data.append([
                    str(idx),
                    str(part.get('name', part.get('handle', 'N/A'))),
                    str(part.get('phone', part.get('user_id', 'N/A'))),
                    str(part.get('message_count', 'N/A')),
                    str(part.get('role', 'N/A')),
                    str(part.get('first_seen', 'N/A')),
                ])

            part_table = Table(part_table_data, colWidths=[25, 110, 100, 70, 70, 80])
            part_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.zps_blue),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('ALIGN', (0, 0), (0, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.Color(0.95, 0.95, 0.95)]),
            ]))
            elements.append(part_table)
            elements.append(Paragraph(
                f'Total participants: {len(participants)}',
                self.styles['BodyText']
            ))
        else:
            elements.append(Paragraph('No participant information available.', self.styles['BodyText']))
