"""
SIM Swap Investigation PDF Report Generator
CyberTrace - Zambia Police Service

Generate professional court-ready SIM swap investigation reports
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime
import os


class SimSwapPDFReport:
    """Generate PDF reports for SIM swap investigations"""

    def __init__(self, data, case, investigator, logo_path=None):
        """
        Initialize PDF report generator

        Args:
            data: Dictionary containing SIM swap investigation results
            case: Case model instance
            investigator: User model instance (investigator)
            logo_path: Path to police logo image
        """
        self.data = data
        self.case = case
        self.investigator = investigator
        self.logo_path = logo_path or 'app/static/img/zp_logo.jpg'
        self.styles = getSampleStyleSheet()
        self.zps_blue = colors.HexColor('#000663')
        self.zps_green = colors.HexColor('#008000')
        self._create_custom_styles()

    def _create_custom_styles(self):
        """Create custom paragraph styles for the report"""
        self.styles.add(ParagraphStyle(
            name='ReportTitle',
            parent=self.styles['Heading1'],
            fontSize=18,
            textColor=self.zps_blue,
            spaceAfter=12,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=self.zps_blue,
            spaceBefore=12,
            spaceAfter=6,
            fontName='Helvetica-Bold'
        ))
        self.styles.add(ParagraphStyle(
            name='BodyText',
            parent=self.styles['Normal'],
            fontSize=10,
            spaceAfter=6
        ))

    def generate(self, pdf_path):
        """Generate the PDF report at the specified path"""
        doc = SimpleDocTemplate(
            pdf_path,
            pagesize=A4,
            rightMargin=50,
            leftMargin=50,
            topMargin=50,
            bottomMargin=50
        )
        elements = []

        # Header
        elements.append(Paragraph('ZAMBIA POLICE SERVICE', self.styles['ReportTitle']))
        elements.append(Paragraph(
            'CONFIDENTIAL - AUTHORIZED USE ONLY',
            ParagraphStyle(
                name='Watermark',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.red,
                alignment=TA_CENTER
            )
        ))
        elements.append(Spacer(1, 12))

        # Case info table
        case_data = [
            ['Case Number:', self.case.case_number if hasattr(self.case, 'case_number') else str(self.case)],
            ['Investigator:', self.investigator.full_name if hasattr(self.investigator, 'full_name') else str(self.investigator)],
            ['Date:', datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')],
        ]
        t = Table(case_data, colWidths=[120, 350])
        t.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 20))

        # Report-specific content
        self._add_content(elements)

        # Footer
        elements.append(Spacer(1, 30))
        elements.append(Paragraph(
            'This report is generated by CyberTrace OSINT Platform for the Zambia Police Service.',
            ParagraphStyle(
                name='Footer',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.grey
            )
        ))

        doc.build(elements)

    def _add_content(self, elements):
        """Add SIM swap investigation content to the report"""

        # Report title
        elements.append(Paragraph(
            '<b>SIM Swap Investigation Report</b>',
            self.styles['ReportTitle']
        ))
        elements.append(Spacer(1, 12))

        # --- Phone Number Information ---
        elements.append(Paragraph('<b>PHONE NUMBER INFORMATION</b>', self.styles['SectionHeader']))

        phone_info = self.data.get('phone_info', {})
        if phone_info:
            phone_rows = [
                ['Phone Number:', str(phone_info.get('number', 'N/A'))],
                ['Carrier:', str(phone_info.get('carrier', 'N/A'))],
                ['Number Type:', str(phone_info.get('number_type', 'N/A'))],
                ['Country:', str(phone_info.get('country', 'N/A'))],
                ['Region:', str(phone_info.get('region', 'N/A'))],
                ['Subscriber Name:', str(phone_info.get('subscriber_name', 'N/A'))],
                ['Account Status:', str(phone_info.get('account_status', 'N/A'))],
                ['Registration Date:', str(phone_info.get('registration_date', 'N/A'))],
            ]
            phone_table = Table(phone_rows, colWidths=[150, 330])
            phone_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ]))
            elements.append(phone_table)
        else:
            elements.append(Paragraph('No phone number information available.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- SIM Change Events ---
        elements.append(Paragraph('<b>SIM CHANGE EVENTS</b>', self.styles['SectionHeader']))

        sim_events = self.data.get('sim_events', [])
        if sim_events:
            event_table_data = [['Date/Time', 'Event Type', 'Old ICCID', 'New ICCID', 'Location', 'Channel']]
            for event in sim_events:
                event_table_data.append([
                    str(event.get('date', 'N/A')),
                    str(event.get('event_type', 'N/A')),
                    str(event.get('old_iccid', 'N/A')),
                    str(event.get('new_iccid', 'N/A')),
                    str(event.get('location', 'N/A')),
                    str(event.get('channel', 'N/A')),
                ])

            event_table = Table(event_table_data, colWidths=[80, 70, 80, 80, 80, 65])
            event_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.zps_blue),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 7),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.Color(0.95, 0.95, 0.95)]),
            ]))
            elements.append(event_table)
            elements.append(Paragraph(
                f'<font color="red"><b>Total SIM change events detected: {len(sim_events)}</b></font>',
                self.styles['BodyText']
            ))
        else:
            elements.append(Paragraph(
                '<font color="green">No SIM change events detected.</font>',
                self.styles['BodyText']
            ))

        elements.append(Spacer(1, 16))

        # --- Correlation Findings ---
        elements.append(Paragraph('<b>CORRELATION FINDINGS</b>', self.styles['SectionHeader']))

        correlations = self.data.get('correlations', [])
        if correlations:
            for idx, corr in enumerate(correlations, 1):
                elements.append(Paragraph(
                    f'<b>Finding #{idx}:</b> {corr.get("description", "N/A")}',
                    self.styles['BodyText']
                ))
                if corr.get('evidence'):
                    elements.append(Paragraph(
                        f'  Evidence: {corr.get("evidence")}',
                        self.styles['BodyText']
                    ))
                if corr.get('confidence'):
                    elements.append(Paragraph(
                        f'  Confidence: {corr.get("confidence")}',
                        self.styles['BodyText']
                    ))
                elements.append(Spacer(1, 4))
        else:
            elements.append(Paragraph('No correlation findings available.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- Timeline Summary ---
        elements.append(Paragraph('<b>TIMELINE SUMMARY</b>', self.styles['SectionHeader']))

        timeline = self.data.get('timeline', [])
        if timeline:
            timeline_table_data = [['Date/Time', 'Event', 'Details']]
            for entry in timeline:
                timeline_table_data.append([
                    str(entry.get('date', 'N/A')),
                    str(entry.get('event', 'N/A')),
                    str(entry.get('details', 'N/A')),
                ])

            tl_table = Table(timeline_table_data, colWidths=[100, 140, 240])
            tl_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.zps_green),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.Color(0.95, 0.95, 0.95)]),
            ]))
            elements.append(tl_table)
        else:
            elements.append(Paragraph('No timeline data available.', self.styles['BodyText']))

        elements.append(Spacer(1, 16))

        # --- Risk Assessment ---
        elements.append(Paragraph('<b>RISK ASSESSMENT</b>', self.styles['SectionHeader']))

        risk = self.data.get('risk_assessment', {})
        if risk:
            risk_score = risk.get('risk_score', 0)
            if risk_score >= 70:
                risk_color = colors.red
            elif risk_score >= 40:
                risk_color = colors.orange
            else:
                risk_color = colors.green

            risk_rows = [
                ['Risk Score:', f'{risk_score}/100'],
                ['Risk Level:', str(risk.get('risk_level', 'N/A'))],
                ['SIM Swap Likelihood:', str(risk.get('sim_swap_likelihood', 'N/A'))],
                ['Fraud Indicator:', str(risk.get('fraud_indicator', 'N/A'))],
                ['Account Takeover Risk:', str(risk.get('account_takeover_risk', 'N/A'))],
            ]
            risk_table = Table(risk_rows, colWidths=[160, 320])
            risk_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('TEXTCOLOR', (1, 0), (1, 0), risk_color),
                ('FONTNAME', (1, 0), (1, 0), 'Helvetica-Bold'),
            ]))
            elements.append(risk_table)

            recommendations = risk.get('recommendations', [])
            if recommendations:
                elements.append(Spacer(1, 8))
                elements.append(Paragraph('<b>Recommendations:</b>', self.styles['BodyText']))
                for rec in recommendations:
                    elements.append(Paragraph(f'  - {rec}', self.styles['BodyText']))
        else:
            elements.append(Paragraph('No risk assessment data available.', self.styles['BodyText']))
