"""Add all new modules: financial, sim_swap, messaging, forensics, social_preservation, correlation, isp_requests, victims

Revision ID: b58825efa9f4
Revises: 
Create Date: 2026-01-29 21:08:23.480724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58825efa9f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('legal_basis', sa.String(length=200), nullable=False),
    sa.Column('required_fields', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threat_actor_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('associated_cases', sa.JSON(), nullable=True),
    sa.Column('associated_indicators', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('ttps', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('account_identifier', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('holder_name', sa.String(length=255), nullable=True),
    sa.Column('is_mule', sa.Boolean(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=True),
    sa.Column('total_inflow', sa.Float(), nullable=True),
    sa.Column('total_outflow', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_accounts_case_id'), ['case_id'], unique=False)

    op.create_table('isp_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('provider_name', sa.String(length=200), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('request_number', sa.String(length=50), nullable=False),
    sa.Column('target_identifier', sa.String(length=255), nullable=False),
    sa.Column('legal_authority', sa.String(length=200), nullable=False),
    sa.Column('warrant_number', sa.String(length=100), nullable=True),
    sa.Column('warrant_document_path', sa.String(length=500), nullable=True),
    sa.Column('date_range_start', sa.DateTime(), nullable=True),
    sa.Column('date_range_end', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sla_deadline', sa.Date(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.Column('response_document_path', sa.String(length=500), nullable=True),
    sa.Column('response_hash', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_number')
    )
    with op.batch_alter_table('isp_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_isp_requests_case_id'), ['case_id'], unique=False)

    op.create_table('preserved_content',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('capture_type', sa.String(length=50), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('screenshot_path', sa.String(length=500), nullable=True),
    sa.Column('screenshot_hash', sa.String(length=64), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('html_hash', sa.String(length=64), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('author_info', sa.JSON(), nullable=True),
    sa.Column('engagement_data', sa.JSON(), nullable=True),
    sa.Column('content_flags', sa.JSON(), nullable=True),
    sa.Column('wayback_url', sa.String(length=500), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('captured_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['captured_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('preserved_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preserved_content_case_id'), ['case_id'], unique=False)

    op.create_table('victims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('victim_type', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('id_number', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('occupation', sa.String(length=200), nullable=True),
    sa.Column('loss_amount', sa.Float(), nullable=True),
    sa.Column('loss_currency', sa.String(length=3), nullable=False),
    sa.Column('loss_type', sa.String(length=50), nullable=True),
    sa.Column('loss_description', sa.Text(), nullable=True),
    sa.Column('date_of_incident', sa.Date(), nullable=True),
    sa.Column('statement_status', sa.String(length=50), nullable=False),
    sa.Column('wants_updates', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('victims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_victims_case_id'), ['case_id'], unique=False)

    op.create_table('content_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('capture_id', sa.String(length=36), nullable=False),
    sa.Column('flag_type', sa.String(length=50), nullable=False),
    sa.Column('legal_reference', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('flagged_content', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('flagged_by', sa.String(length=36), nullable=False),
    sa.Column('flagged_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['capture_id'], ['preserved_content.id'], ),
    sa.ForeignKeyConstraint(['flagged_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_flags_capture_id'), ['capture_id'], unique=False)

    op.create_table('correlation_indicators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=True),
    sa.Column('indicator_type', sa.String(length=50), nullable=False),
    sa.Column('indicator_value', sa.String(length=500), nullable=False),
    sa.Column('source_module', sa.String(length=100), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('correlation_indicators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correlation_indicators_case_id'), ['case_id'], unique=False)

    op.create_table('financial_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('sender_account', sa.String(length=255), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('receiver_account', sa.String(length=255), nullable=False),
    sa.Column('receiver_name', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('reference_number', sa.String(length=255), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('is_suspicious', sa.Boolean(), nullable=True),
    sa.Column('mule_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_transactions_case_id'), ['case_id'], unique=False)

    op.create_table('forensic_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('doc_metadata', sa.JSON(), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('creator_tool', sa.String(length=200), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('modification_date', sa.DateTime(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('embedded_objects', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('analyzed_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analyzed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forensic_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forensic_documents_case_id'), ['case_id'], unique=False)

    op.create_table('forensic_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('exif_data', sa.JSON(), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('gps_location_name', sa.String(length=500), nullable=True),
    sa.Column('device_make', sa.String(length=200), nullable=True),
    sa.Column('device_model', sa.String(length=200), nullable=True),
    sa.Column('capture_date', sa.DateTime(), nullable=True),
    sa.Column('modification_history', sa.JSON(), nullable=True),
    sa.Column('ela_result', sa.JSON(), nullable=True),
    sa.Column('manipulation_detected', sa.Boolean(), nullable=True),
    sa.Column('manipulation_confidence', sa.Float(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('reverse_search_results', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('analyzed_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analyzed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forensic_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forensic_images_case_id'), ['case_id'], unique=False)

    op.create_table('messaging_exports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('chat_type', sa.String(length=20), nullable=False),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('date_range_start', sa.DateTime(), nullable=True),
    sa.Column('date_range_end', sa.DateTime(), nullable=True),
    sa.Column('extracted_links', sa.JSON(), nullable=True),
    sa.Column('extracted_phones', sa.JSON(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messaging_exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messaging_exports_case_id'), ['case_id'], unique=False)

    op.create_table('sim_swap_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('carrier', sa.String(length=100), nullable=False),
    sa.Column('old_iccid', sa.String(length=50), nullable=True),
    sa.Column('new_iccid', sa.String(length=50), nullable=True),
    sa.Column('old_imsi', sa.String(length=50), nullable=True),
    sa.Column('new_imsi', sa.String(length=50), nullable=True),
    sa.Column('swap_date', sa.DateTime(), nullable=False),
    sa.Column('swap_type', sa.String(length=50), nullable=False),
    sa.Column('associated_compromises', sa.JSON(), nullable=True),
    sa.Column('detection_method', sa.String(length=100), nullable=True),
    sa.Column('carrier_data', sa.JSON(), nullable=True),
    sa.Column('correlation_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sim_swap_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sim_swap_events_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sim_swap_events_phone_number'), ['phone_number'], unique=False)

    op.create_table('transaction_flows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('source_account_id', sa.String(length=36), nullable=False),
    sa.Column('destination_account_id', sa.String(length=36), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('first_transaction', sa.DateTime(), nullable=True),
    sa.Column('last_transaction', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['destination_account_id'], ['financial_accounts.id'], ),
    sa.ForeignKeyConstraint(['source_account_id'], ['financial_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_flows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_flows_case_id'), ['case_id'], unique=False)

    op.create_table('victim_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('victim_id', sa.String(length=36), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent_via', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('sent_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['victim_id'], ['victims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('victim_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_victim_notifications_victim_id'), ['victim_id'], unique=False)

    op.create_table('victim_statements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('victim_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('recorded_by', sa.String(length=36), nullable=False),
    sa.Column('statement_text', sa.Text(), nullable=False),
    sa.Column('statement_date', sa.DateTime(), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['victim_id'], ['victims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('victim_statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_victim_statements_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_victim_statements_victim_id'), ['victim_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('export_id', sa.String(length=36), nullable=False),
    sa.Column('sender', sa.String(length=200), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('has_media', sa.Boolean(), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('flag_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['export_id'], ['messaging_exports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_export_id'), ['export_id'], unique=False)

    op.create_table('correlation_matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('indicator_id_a', sa.String(length=36), nullable=False),
    sa.Column('indicator_id_b', sa.String(length=36), nullable=False),
    sa.Column('case_id_a', sa.String(length=36), nullable=False),
    sa.Column('case_id_b', sa.String(length=36), nullable=False),
    sa.Column('match_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id_a'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['case_id_b'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['indicator_id_a'], ['correlation_indicators.id'], ),
    sa.ForeignKeyConstraint(['indicator_id_b'], ['correlation_indicators.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('correlation_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correlation_matches_indicator_id_a'), ['indicator_id_a'], unique=False)
        batch_op.create_index(batch_op.f('ix_correlation_matches_indicator_id_b'), ['indicator_id_b'], unique=False)

    op.create_table('messaging_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('export_id', sa.String(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('first_message', sa.DateTime(), nullable=True),
    sa.Column('last_message', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['export_id'], ['messaging_exports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messaging_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messaging_contacts_export_id'), ['export_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messaging_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messaging_contacts_export_id'))

    op.drop_table('messaging_contacts')
    with op.batch_alter_table('correlation_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correlation_matches_indicator_id_b'))
        batch_op.drop_index(batch_op.f('ix_correlation_matches_indicator_id_a'))

    op.drop_table('correlation_matches')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_export_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('victim_statements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_victim_statements_victim_id'))
        batch_op.drop_index(batch_op.f('ix_victim_statements_case_id'))

    op.drop_table('victim_statements')
    with op.batch_alter_table('victim_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_victim_notifications_victim_id'))

    op.drop_table('victim_notifications')
    with op.batch_alter_table('transaction_flows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_flows_case_id'))

    op.drop_table('transaction_flows')
    with op.batch_alter_table('sim_swap_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sim_swap_events_phone_number'))
        batch_op.drop_index(batch_op.f('ix_sim_swap_events_case_id'))

    op.drop_table('sim_swap_events')
    with op.batch_alter_table('messaging_exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messaging_exports_case_id'))

    op.drop_table('messaging_exports')
    with op.batch_alter_table('forensic_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forensic_images_case_id'))

    op.drop_table('forensic_images')
    with op.batch_alter_table('forensic_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forensic_documents_case_id'))

    op.drop_table('forensic_documents')
    with op.batch_alter_table('financial_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_transactions_case_id'))

    op.drop_table('financial_transactions')
    with op.batch_alter_table('correlation_indicators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correlation_indicators_case_id'))

    op.drop_table('correlation_indicators')
    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_flags_capture_id'))

    op.drop_table('content_flags')
    with op.batch_alter_table('victims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_victims_case_id'))

    op.drop_table('victims')
    with op.batch_alter_table('preserved_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preserved_content_case_id'))

    op.drop_table('preserved_content')
    with op.batch_alter_table('isp_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_isp_requests_case_id'))

    op.drop_table('isp_requests')
    with op.batch_alter_table('financial_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_accounts_case_id'))

    op.drop_table('financial_accounts')
    op.drop_table('threat_actor_profiles')
    op.drop_table('request_templates')
    # ### end Alembic commands ###
